#importing libraries
from csv import reader
from csv import writer
#preparing data for logistic regrerssion model
#converting state feature values into integer
def StateToInt(state):
    statelist = ['Telangana','Uttar Pradesh','Maharashtra','Gujarat','Rajasthan','Kerala','West Bengal','Uttarakhand','Andhra Pradesh','Haryana','Punjab','Jammu & Kashmir','Andaman & Nicobar Islands','Tamil Nadu','Bihar','Arunachal Pradesh','Odisha','Assam','Karnataka','Madhya Pradesh','Chhattisgarh','Chandigarh','NCT OF Delhi','Jharkhand','Dadra & Nagar Haveli','Daman & Diu','Himachal Pradesh','Manipur','Lakshadweep','Mizoram','Nagaland','Goa','Puducherry','Meghalaya','Sikkim','Tripura']
    return (statelist.index(state) + 1)
#converting constituency into int
def ConvertConstituencyToInt(constituency):
    constituencylist = ['ADILABAD','AGRA','AHMADNAGAR','AHMEDABAD EAST','AHMEDABAD WEST','AJMER','AKBARPUR','AKOLA','ALAPPUZHA','ALATHUR','ALIGARH','ALIPURDUARS','ALLAHABAD','ALMORA','ALWAR','AMALAPURAM','AMBALA','AMBEDKAR NAGAR','AMETHI','AMRAVATI','AMRELI','AMRITSAR','AMROHA','ANAKAPALLI','ANAND','ANANDPUR SAHIB','ANANTAPUR','ANANTNAG','ANDAMAN & NICOBAR ISLANDS','AONLA','ARAKKONAM','ARAMBAGH','ARANI','ARARIA','ARRAH','ARUKU','ARUNACHAL EAST','ARUNACHAL WEST','ASANSOL','ASKA','ATTINGAL','AURANGABAD','AUTONOMOUS DISTRICT','AZAMGARH','BADAUN','BAGALKOT','BAGHPAT','BAHARAMPUR','BAHRAICH','BALAGHAT','BALASORE','BALLIA','BALURGHAT','BANASKANTHA','BANDA','BANGALORE CENTRAL','BANGALORE NORTH','BANGALORE RURAL','BANGALORE SOUTH','BANGAON','BANKA','BANKURA','BANSGAON','BANSWARA','BAPATLA','BARABANKI','BARAMATI','BARAMULLA','BARASAT','BARDHAMAN DURGAPUR','BARDHAMAN PURBA','BARDOLI','BAREILLY','BARGARH','BARMER','BARPETA','BARRACKPORE','BASIRHAT','BASTAR','BASTI','BATHINDA','BEED','BEGUSARAI','BELGAUM','BELLARY','BERHAMPUR','BETUL','BHADOHI','BHADRAK','BHAGALPUR','BHANDARA - GONDIYA','BHARATPUR','BHARUCH','BHAVNAGAR','BHILWARA','BHIND','BHIWANDI','BHIWANI-MAHENDRAGARH','BHONGIR','BHOPAL','BHUBANESWAR','BIDAR','BIJAPUR','BIJNOR','BIKANER (SC)','BILASPUR','BIRBHUM','BISHNUPUR','BOLANGIR','BOLPUR','BULANDSHAHR','BULDHANA','BUXAR','CHALAKUDY','CHAMARAJANAGAR','CHANDAULI','CHANDIGARH','CHANDNI CHOWK','CHANDRAPUR','CHATRA','CHENNAI CENTRAL','CHENNAI NORTH','CHENNAI SOUTH','CHEVELLA','CHHINDWARA','CHHOTA UDAIPUR','CHIDAMBARAM','CHIKKBALLAPUR','CHIKKODI','CHITRADURGA','CHITTOOR','CHITTORGARH','CHURU','COIMBATORE','COOCH BEHAR','CUDDALORE','CUTTACK','DADRA AND NAGAR HAVELI','DAHOD','DAKSHINA KANNADA','DAMAN & DIU','DAMOH','DARBHANGA','DARJEELING','DAUSA','DAVANAGERE','DEORIA','DEWAS','DHANBAD','DHAR','DHARMAPURI','DHARWAD','DHAURAHRA','DHENKANAL','DHUBRI','DHULE','DIAMOND HARBOUR','DIBRUGARH','DINDIGUL','DINDORI','DOMARIYAGANJ','DUM DUM','DUMKA','DURG','EAST DELHI','ELURU','ERNAKULAM','ERODE','ETAH','ETAWAH','FAIZABAD','FARIDABAD','FARIDKOT','FARRUKHABAD','FATEHGARH SAHIB','FATEHPUR','FATEHPUR SIKRI','FIROZABAD','FIROZPUR','GADCHIROLI-CHIMUR','GANDHINAGAR','GANGANAGAR','GARHWAL','GAUHATI','GAUTAM BUDDHA NAGAR','GAYA (SC)','GHATAL','GHAZIABAD','GHAZIPUR','GHOSI','GIRIDIH','GODDA','GONDA','GOPALGANJ (SC)','GORAKHPUR','GULBARGA','GUNA','GUNTUR','GURDASPUR','GURGAON','GWALIOR','HAJIPUR (SC)','HAMIRPUR','HARDOI','HARDWAR','HASSAN','HATHRAS','HATKANANGLE','HAVERI','HAZARIBAGH','HINDUPUR','HINGOLI','HISAR','HOOGHLY','HOSHANGABAD','HOSHIARPUR','HOWRAH','HYDERABAD','IDUKKI','INDORE','INNER MANIPUR','JABALPUR','JADAVPUR','JAGATSINGHPUR','JAHANABAD','JAIPUR','JAIPUR RURAL','JAJPUR','JALANDHAR','JALAUN','JALGAON','JALNA','JALORE','JALPAIGURI','JAMMU','JAMNAGAR','JAMSHEDPUR','JAMUI (SC)','JANGIPUR','JANJGIR-CHAMPA','JAUNPUR','JAYNAGAR','JHALAWAR-BARAN','JHANJHARPUR','JHANSI','JHARGRAM','JHUNJHUNU','JODHPUR','JORHAT','JUNAGADH','KACHCHH','KADAPA','KAIRANA','KAISERGANJ','KAKINADA','KALAHANDI','KALIABOR','KALLAKURICHI','KALYAN','KANCHEEPURAM','KANDHAMAL','KANGRA','KANKER','KANNAUJ','KANNIYAKUMARI','KANNUR','KANPUR','KANTHI','KARAKAT','KARAULI-DHOLPUR','KARIMGANJ','KARIMNAGAR','KARNAL','KARUR','KASARAGOD','KATIHAR','KAUSHAMBI','KENDRAPARA','KEONJHAR','KHADOOR SAHIB','KHAGARIA','KHAJURAHO','KHAMMAM','KHANDWA','KHARGONE','KHEDA','KHERI','KHUNTI','KISHANGANJ','KODARMA','KOKRAJHAR','KOLAR','KOLHAPUR','KOLKATA DAKSHIN','KOLKATA UTTAR','KOLLAM','KOPPAL','KORAPUT','KORBA','KOTA','KOTTAYAM','KOZHIKODE','KRISHNAGIRI','KRISHNANAGAR','KURNOOL','KURUKSHETRA','KUSHI NAGAR','LADAKH','LAKHIMPUR','LAKSHADWEEP','LALGANJ','LATUR','LOHARDAGA','LUCKNOW','LUDHIANA','MACHHLISHAHR','MACHILIPATNAM','MADHA','MADHEPURA','MADHUBANI','MADURAI','MAHABUBABAD','MAHARAJGANJ','MAHASAMUND','MAHBUBNAGAR','MAHESANA','MAINPURI','MALAPPURAM','MALDAHA DAKSHIN','MALDAHA UTTAR','MALKAJGIRI','MANDI','MANDLA','MANDSOUR','MANDYA','MANGALDOI','MATHURA','MATHURAPUR','MAVAL','MAVELIKKARA','MAYILADUTHURAI','MAYURBHANJ','MEDAK','MEDINIPUR','MEERUT','MIRZAPUR','MISRIKH','MIZORAM','MOHANLALGANJ','MORADABAD','MORENA','MUMBAI NORTH','MUMBAI NORTH CENTRAL','MUMBAI NORTH EAST','MUMBAI NORTH WEST','MUMBAI SOUTH','MUMBAI SOUTH CENTRAL','MUNGER','MURSHIDABAD','MUZAFFARNAGAR','MUZAFFARPUR','MYSORE','NABARANGPUR','NAGALAND','NAGAPATTINAM','NAGARKURNOOL','NAGAUR','NAGINA','NAGPUR','NAINITAL-UDHAMSINGH NAGAR','NALANDA','NALGONDA','NAMAKKAL','NANDED','NANDURBAR','NANDYAL','NARASARAOPET','NARSAPURAM','NASHIK','NAVSARI','NAWADA','NELLORE','NEW DELHI','NILGIRIS','NIZAMABAD','NORTH EAST DELHI','NORTH GOA','NORTH WEST DELHI','NOWGONG','ONGOLE','OSMANABAD','OUTER MANIPUR','PALAKKAD','PALAMAU','PALGHAR','PALI','PANCHMAHAL','PARBHANI','PASCHIM CHAMPARAN','PATALIPUTRA','PATAN','PATHANAMTHITTA','PATIALA','PATNA SAHIB','PEDDAPALLE','PERAMBALUR','PHULPUR','PILIBHIT','POLLACHI','PONNANI','PORBANDAR','PRATAPGARH','PUDUCHERRY','PUNE','PURI','PURNIA','PURULIA','PURVI CHAMPARAN','RAE BARELI','RAICHUR','RAIGAD','RAIGANJ','RAIGARH','RAIPUR','RAJAHMUNDRY','RAJAMPET','RAJGARH','RAJKOT','RAJMAHAL','RAJNANDGAON','RAJSAMAND','RAMANATHAPURAM','RAMPUR','RAMTEK','RANAGHAT','RANCHI','RATLAM','RATNAGIRI - SINDHUDURG','RAVER','REWA','ROBERTSGANJ','ROHTAK','SABARKANTHA','SAGAR','SAHARANPUR','SALEM','SALEMPUR','SAMASTIPUR (SC)','SAMBALPUR','SAMBHAL','SANGLI','SANGRUR','SANT KABIR NAGAR','SARAN','SARGUJA','SASARAM (SC)','SATARA','SATNA','SECUNDRABAD','SHAHDOL','SHAHJAHANPUR','SHEOHAR','SHILLONG','SHIMLA','SHIMOGA','SHIRDI','SHIRUR','SHRAWASTI','SIDHI','SIKAR','SIKKIM','SILCHAR','SINGHBHUM','SIRSA','SITAMARHI','SITAPUR','SIVAGANGA','SIWAN','SOLAPUR','SONIPAT','SOUTH DELHI','SOUTH GOA','SRERAMPUR','SRIKAKULAM','SRINAGAR','SRIPERUMBUDUR','SULTANPUR','SUNDARGARH','SUPAUL','SURAT','SURENDRANAGAR','TAMLUK','TEHRI GARHWAL','TENKASI','TEZPUR','THANE','THANJAVUR','THENI','THIRUVALLUR','THIRUVANANTHAPURAM','THOOTHUKKUDI','THRISSUR','TIKAMGARH','TIRUCHIRAPPALLI','TIRUNELVELI','TIRUPATI','TIRUPPUR','TIRUVANNAMALAI','TONK-SAWAI MADHOPUR','TRIPURA EAST','TRIPURA WEST','TUMKUR','TURA','UDAIPUR','UDHAMPUR','UDUPI CHIKMAGALUR','UJIARPUR','UJJAIN','ULUBERIA','UNNAO','UTTARA KANNADA','VADAKARA','VADODARA','VAISHALI','VALMIKI NAGAR','VALSAD','VARANASI','VIDISHA','VIJAYAWADA','VILUPPURAM','VIRUDHUNAGAR','VISAKHAPATNAM','VIZIANAGARAM','WARANGAL','WARDHA','WAYANAD','WEST DELHI','YAVATMAL-WASHIM','ZAHIRABAD']
    return (constituencylist.index(constituency)+1)
#converting party name into int
def PartyNameToInt(party):
    partylist = ['BJP','JP','TRS','INC','NOTA','BSP','NCP','VBA','APoI','CPI(M)','BDJS','AITC','RSP','SP','YSRCP','TDP','JnP','INLD','SBSP','IND','SHS','AAP','SAD','JKN','JKPDP','JPC','DMK','PMK','NTK','MNM','AIADMK','RJD','CPI(ML)(L)','SSD','PPA','JD(S)','NPEP','BMUP','BJD','AIMIM','HAMS','AHFBK','PPID','SPL','ASDC','RLD','PSPL','JD(U)','BTP','AIFB','AGP','AIUDF','ABSKP','PUNEKP','RTORP','JNJP','LTSP','RVNP','JANADIP','SDPI','DMDK','ABGP','VCK','JMM','LIP','JDR','MOSP','MADP','AJPR','PMP','BBMP','AJSUP','JVM','RMPOI','LJP','BJKVP','SWP','NEINDP','RSPSR','ravp','RSOSP','BLSP','WPOI','SUCI(C)','SJDD','ANC','JDL','VSIP','AAM','JKP','BOPF','UPPL','CPIM','GGP','KEC(M)','KEC','JAPL','AKBMP','TJS','IUML','BSCP','ADAL','BRPI','MNF','PRISMP','VPI','YKP','NDPP','RLTP','RAHIS','NPF','BLSD','BVA','NAWPP','AINRC','BNDl','MSHP','BARESP','BLRP','AIPF','WAP','VCSMP','SAD(M)','UDP','SKM','SDF','PDP','JHP','TMC(M)','IPFT','JKNPP','DSSP','AHNP','PHJSP']
    return (partylist.index(party)+1)
#converting gender into integer
def GenderToInt(gender):
    genderlist = ['MALE','FEMALE','Not Given']
    return (genderlist.index(gender)+1)
#convert category into int
def CategoryToInt(category):
    categorylist = ['ST','Not Given','SC','GENERAL']
    return (categorylist.index(category)+1)
#converting education into integer
def EducationToInt(education):
    educationlist = ['12th Pass','Post Graduate','Not Given','Doctorate','Graduate','Others','10th Pass','8th Pass','Graduate Professional','Literate','Illiterate','5th Pass','Not Available']
    return (educationlist.index(education)+1 )
#reading and converting data into desired output file for machine learning techniques
with open('C:\Ruchita\MSc_Data_Science\Module 3-7072 ML\CW_7072\LS_2.0.csv', 'r') as read_obj, \
     open('C:\Ruchita\MSc_Data_Science\Module 3-7072 ML\CW_7072\LS_2.0_output.csv','w',newline='\n') as write_obj:
    csv_reader = reader(read_obj)
    csv_writer = writer(write_obj)
    for row in csv_reader:
        #Append Feature column at the end
        row.append(row[3])
        del row[3]

        if row[0] == 'STATE':
            pass
        else:
            #Convert state string to a numerical value
            row[0] = StateToInt(row[0])
            row[1] = ConvertConstituencyToInt(row[1])
            row[3] = PartyNameToInt(row[3])
            row[5] = GenderToInt(row[5])
            row[8] = CategoryToInt(row[8])
            row[9] = EducationToInt(row[9])

            del row[2]
            del row[3]
            del row[8]
            del row[8]
            del row[8]
            del row[8]
            del row[8]
            del row[8]
            del row[8]
            del row[8]

            csv_writer.writerow(row)


